Solution
mate-academy/py-can-access-google-page pull request #312
Opened 2023-02-24 10:34 UTC by Litvinenko23

2023-02-27 13:55 UTC, Serhii-Leonenko requested changes

2023-02-27 13:55 UTC, Serhii-Leonenko commented on app/test_main.py
> +    # Mock the valid_google_url function to always return True
remove redundant comments

2023-02-27 13:55 UTC, Serhii-Leonenko commented on app/test_main.py
> +    assert can_access_google_page("https://www.google.com") == "Not accessible"
add tests for case when both are False, also try to remove code duplicates

2023-02-28 13:54 UTC, closed without merging

2023-03-01 15:31 UTC, Serhii-Leonenko requested changes
Use @pytest.mark.parametrize for DRY

2023-03-02 17:26 UTC, wQuelS requested changes

2023-03-02 17:26 UTC, wQuelS commented on app/test_main.py
> +        ("https://www.goole.com", False, False, "Not accessible"),
Provided more descriptive message

2023-03-02 17:26 UTC, wQuelS commented on app/test_main.py
> +from app.main import can_access_google_page
make your imports according to PEP8 convention. Blank lines between group of imports, their order, etc.