added test
mate-academy/py-can-access-google-page pull request #652
Opened 2023-12-21 11:18 UTC by BGBroth

2023-12-21 12:52 UTC, Polyakiv-Andrey requested changes
Tests not passed!

2023-12-22 12:28 UTC, vsmutok requested changes

2023-12-22 12:28 UTC, vsmutok commented on app/test_main.py
> +    assert result == "Not accessible"
use  `@pytest.mark.parametrize`

2023-12-23 11:49 UTC, pavlejviki requested changes

2023-12-23 11:49 UTC, pavlejviki commented on app/test_main.py
> +        mock_has_internet_connection: Callable,
wrong type annotation for mock objects

2023-12-23 18:52 UTC, vsmutok requested changes
please fix flake8 error

2024-07-09 09:08 UTC, closed without merging